### PR TITLE
installation and configuration of the Gsap and Lenis libraries + anim…

### PR DESCRIPTION
**Pull request by Desbiens-Mickael**
…ation.

### CODE REVIEW

**Review by AlicePhkeo — APPROVED** [review]
wouaw! good job

**Comment by AlicePhkeo** [comment]
beautiful

**Review by Lazharlaz — COMMENTED** [review]
super !

**Comment by Lazharlaz** [comment]
super !

**Review by Lazharlaz — APPROVED** [review]
niquel

**Pull request merged**
